GET http://localhost:8087/api/v2/user
###
POST http://localhost:8087/api/v2/auth/register
Content-Type: application/json

{
    "email": "phatdoan.1014@gmail.com",
    "password": "123456"
}
###
POST http://localhost:8087/api/v2/auth/login
Content-Type: application/json

{
    "email": "phatdoan.1014@gmail.com",
    "password": "123456"
}

###
GET http://localhost:8087/api/v2/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJwaGF0ZG9hbi4xMDE0QGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIxIiwiaWF0IjoxNzI3MTY5Nzc4LCJleHAiOjE3Mjc2MDE3Nzh9.8m5oldvPJ2p8CiJv-Wqq28PIPW9dobbB_OVZrM8HkwU

### 
GET http://localhost:8087/api/v2/book/?name=journey