GET http://localhost:8087/api/v2/user
###
POST http://localhost:8087/api/v2/auth/register
Content-Type: application/json

{
    "email": "phatdoan.1014@gmail.com",
    "password": "123456"
}
###
POST http://localhost:8087/api/v2/auth/login
Content-Type: application/json

{
    "email": "admin1@gmail.com",
    "password": "123456"
}

###
GET http://localhost:8087/api/v2/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbjFAZ21haWwuY29tIiwicm9sZV9jb2RlIjoiUjMiLCJpYXQiOjE3MjcxMjMxMTUsImV4cCI6MTcyNzU1NTExNX0.hpPs6L8ZJvhnJqBqyNMAgSKAInCcA284aaHUp6dDpOA